<script module lang="ts">
	export type OnboardTab = 'qr' | 'download' | 'share' | 'config';
</script>

<script lang="ts">
	/**
	 * Onboarding modal shown after creating a peer (and from row actions):
	 * QR / Download / Share link / Config text, with a Full | Split tunnel-mode
	 * control that changes the `allowed_ips` override for QR and download live.
	 */
	import { Download, FileText, Link2, QrCode } from 'lucide-svelte';
	import { api, isAbortError, toApiError } from '$lib/api';
	import type { Peer } from '$lib/api/types';
	import { toast } from '$lib/stores/toast.svelte';
	import { FULL_TUNNEL, LAN_RANGES, interfaceSubnets, isFullTunnel, joinList } from '$lib/utils/format';
	import Alert from '$lib/components/ui/Alert.svelte';
	import Button from '$lib/components/ui/Button.svelte';
	import CodeBlock from '$lib/components/ui/CodeBlock.svelte';
	import CopyButton from '$lib/components/ui/CopyButton.svelte';
	import Dialog from '$lib/components/ui/Dialog.svelte';
	import SegmentedControl from '$lib/components/ui/SegmentedControl.svelte';
	import Skeleton from '$lib/components/ui/Skeleton.svelte';
	import Tabs from '$lib/components/ui/Tabs.svelte';
	import ShareLinkPanel from './ShareLinkPanel.svelte';

	interface Props {
		open: boolean;
		peer: Peer | null;
		/** Interface address, used to build the split-tunnel override. */
		ifaceAddress?: string;
		initialTab?: OnboardTab;
		/** True right after creation: shows the "peer created" banner. */
		justCreated?: boolean;
	}

	let {
		open = $bindable(false),
		peer,
		ifaceAddress = '',
		initialTab = 'qr',
		justCreated = false
	}: Props = $props();

	type TunnelMode = 'full' | 'split';
	let tab = $state<OnboardTab>('qr');
	let mode = $state<TunnelMode>('full');
	let qrUrl = $state<string | null>(null);
	let config = $state<string | null>(null);
	let loading = $state(false);
	let error = $state<string | null>(null);
	let downloading = $state(false);
	let abort: AbortController | null = null;

	const peerIsFull = $derived(peer ? isFullTunnel(peer.client_allowed_ips) : true);
	const splitRoutes = $derived.by(() => {
		if (peer && !peerIsFull) return peer.client_allowed_ips;
		const subnets = interfaceSubnets(ifaceAddress);
		return joinList([...LAN_RANGES, ...subnets.filter((s) => !LAN_RANGES.includes(s))]);
	});
	/** The allowed_ips override sent to the API (undefined = stored value). */
	const override = $derived.by(() => {
		if (mode === 'full') return peerIsFull ? undefined : FULL_TUNNEL;
		return peerIsFull ? splitRoutes : undefined;
	});
	const effectiveRoutes = $derived(override ?? peer?.client_allowed_ips ?? '');

	$effect(() => {
		if (open && peer) {
			tab = initialTab;
			mode = isFullTunnel(peer.client_allowed_ips) ? 'full' : 'split';
		}
	});

	$effect(() => {
		if (!open || !peer || !peer.has_private_key) return;
		const id = peer.id;
		const ov = override;
		abort?.abort();
		abort = new AbortController();
		const signal = abort.signal;
		loading = true;
		error = null;
		void (async () => {
			try {
				const [blob, text] = await Promise.all([
					api.peers.qr(id, ov, signal),
					api.peers.config(id, ov, signal)
				]);
				if (signal.aborted) return;
				if (qrUrl) URL.revokeObjectURL(qrUrl);
				qrUrl = URL.createObjectURL(blob);
				config = text;
			} catch (err) {
				if (isAbortError(err)) return;
				error = toApiError(err).detail;
			} finally {
				if (!signal.aborted) loading = false;
			}
		})();
		return () => abort?.abort();
	});

	$effect(() => () => {
		if (qrUrl) URL.revokeObjectURL(qrUrl);
	});

	async function download() {
		if (!peer) return;
		downloading = true;
		try {
			await api.peers.downloadConfig(peer.id, peer.name, override);
		} catch (err) {
			toast.error('Download failed', { description: toApiError(err).detail });
		} finally {
			downloading = false;
		}
	}

	const tabs = [
		{ id: 'qr' as const, label: 'QR code', icon: QrCode },
		{ id: 'download' as const, label: 'Download', icon: Download },
		{ id: 'share' as const, label: 'Share link', icon: Link2 },
		{ id: 'config' as const, label: 'Config', icon: FileText }
	];
</script>

{#if peer}
	<Dialog
		bind:open
		title={justCreated ? `${peer.name} is ready` : `Connect ${peer.name}`}
		description={`Peer on ${peer.interface_name} · ${peer.allowed_ips}`}
		size="lg"
	>
		{#snippet header()}
			<Tabs {tabs} bind:value={tab} label="Onboarding options" idPrefix="onboard" />
		{/snippet}

		<div class="flex flex-col gap-4">
			{#if !peer.has_private_key}
				<Alert tone="warning" title="No private key stored">
					This peer's private key was not generated by TunnBox, so a client configuration cannot be produced.
					Rotate the keys to generate a new pair, or configure the client manually with the interface's public
					key.
				</Alert>
			{:else}
				{#if tab !== 'share'}
					<div class="flex flex-wrap items-center justify-between gap-3">
						<SegmentedControl
							bind:value={mode}
							label="Tunnel mode"
							options={[
								{ value: 'full', label: 'Full tunnel' },
								{ value: 'split', label: 'Split tunnel' }
							]}
						/>
						<p class="min-w-0 truncate font-mono text-[12px] text-fg-subtle" title={effectiveRoutes}>
							{effectiveRoutes}
						</p>
					</div>
				{/if}

				{#if error}
					<Alert tone="danger">{error}</Alert>
				{/if}

				{#if tab === 'qr'}
					<div
						id="onboard-panel-qr"
						role="tabpanel"
						aria-labelledby="onboard-qr"
						class="flex flex-col items-center gap-3"
					>
						<div class="rounded-lg border border-border bg-white p-3">
							{#if qrUrl && !loading}
								<img
									src={qrUrl}
									alt={`QR code with the WireGuard configuration for ${peer.name}`}
									width="240"
									height="240"
									class="block h-60 w-60"
								/>
							{:else}
								<Skeleton class="h-60 w-60" rounded="md" />
							{/if}
						</div>
						<p class="max-w-sm text-center text-[13px] text-fg-muted">
							Open the WireGuard app on the device, choose <strong>Add tunnel → Scan QR code</strong> and point
							the camera here.
						</p>
					</div>
				{:else if tab === 'download'}
					<div
						id="onboard-panel-download"
						role="tabpanel"
						aria-labelledby="onboard-download"
						class="flex flex-col items-center gap-4 py-4 text-center"
					>
						<div
							class="flex h-14 w-14 items-center justify-center rounded-lg bg-accent-soft text-accent"
							aria-hidden="true"
						>
							<Download class="h-7 w-7" />
						</div>
						<div>
							<p class="font-medium text-fg">{peer.name}.conf</p>
							<p class="mt-1 max-w-sm text-[13px] text-fg-muted">
								Import the file in the WireGuard app (Import tunnel from file). It contains the private key —
								keep it safe.
							</p>
						</div>
						<Button variant="primary" onclick={download} loading={downloading} disabled={loading}>
							<Download class="h-4 w-4" aria-hidden="true" />
							Download configuration
						</Button>
					</div>
				{:else if tab === 'config'}
					<div
						id="onboard-panel-config"
						role="tabpanel"
						aria-labelledby="onboard-config"
						class="flex flex-col gap-3"
					>
						{#if config && !loading}
							<CodeBlock code={config} label="Client configuration" />
							<div class="flex justify-end">
								<CopyButton text={config} label="Copy configuration" variant="button" />
							</div>
						{:else}
							<Skeleton class="h-56 w-full" rounded="md" />
						{/if}
					</div>
				{/if}
			{/if}

			{#if tab === 'share'}
				<div id="onboard-panel-share" role="tabpanel" aria-labelledby="onboard-share">
					<ShareLinkPanel {peer} />
				</div>
			{/if}
		</div>

		{#snippet footer()}
			<Button variant="secondary" onclick={() => (open = false)}>Done</Button>
		{/snippet}
	</Dialog>
{/if}
